language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.2
env:
    global:
        - TEST_COMMAND="vendor/bin/phpunit"

matrix:
    fast_finish: true

    include:
        - php: 5.6
          env: SYMFONY_VERSION=3.2.*
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.1
          env: SYMFONY_VERSION=3.2.*

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND
